---
- hosts: all
  remote_host: root
  tasks:
  - name: install zabbix rpm source
    yum:
      name: http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm
      state: installed
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Redhat'
  - name: donwload ubuntu deb
    get_url:
      url: http://repo.zabbix.com/zabbix/3.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.4-1+xenial_all.deb
      dest: /tmp/zabbix.deb
    when: ansible_distribution == 'Ubuntu'
  - name: install zabbix source
    apt:
      deb: /tmp/zabbix.deb
    when: ansible_distribution == 'Ubuntu'
  - name: install centos zabbix package
    yum:
      name: "{{ item }}"
      state: installed
    with_items:
      - zabbix-server-mysql
      - zabbix-proxy-mysql
      - zabbix-web-mysql
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Redhat'
  - name: install ubuntu zabbix package
    apt:
      name: zabbix-agent
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'
  - name: modify zabbix config
    replace:
      path:  /etc/zabbix/zabbix_server.conf 
      regexp: DBUser=zabbix
      replace: DBUser=root
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Redhat'
  - name: import zabbix sql table
    shell: zcat /usr/share/doc/zabbix-server-mysql-3.4.7/create.sql.gz | mysql -uroot zabbix
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Redhat'
  - name: disable selinux
    selinux:
      state: disabled 
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Redhat'
  - name: start zabbix-server
    systemd:
      name: zabbix-server
      state: started
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Redhat'
  - name: start zabbix-agent
    systemd:
      name: zabbix-agent
      state: started
    when: ansible_distribution == 'Ubuntu'

